/**
 * Course: IT252 - Intermediate Java Programming II
 * Filename:SalesTracker.java
 * Module: Driver Application 
 * Created: 04/05/2016
 * Modified:04/14/2016
 * 
 * Purpose: This driver application will show create and display a GUI window that will capture sales representative information.
 * The window will use different elements of the Swing class and will also do data validation on all of the keyed input.
 * Modification:
 * 04/05/2016 Created project and screen.
 * 04/05/2016 Created call to component to write data to a file. Clear entry if data write successful
 * 
 */
package IT252IP2;

import java.awt.Color;
import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import javax.swing.JOptionPane;

/**
 *
 * @author Duane Osburn
 */
public class SalesTracker extends javax.swing.JFrame {

    /**
     * Creates new form SalesTracker
     * Also makes sure that the error text fields are set to invisible to begin with.
     */
    public SalesTracker() {
        initComponents();
        repIDError.setVisible(false);
        firstNameErr.setVisible(false);
        lastNameErr.setVisible(false);
        officeError.setVisible(false);
        bookError.setVisible(false);
        paperError.setVisible(false);
        contactError.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        repIDIn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        repFNameIn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        repLNameIn = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        offSupIn = new javax.swing.JTextField();
        bookIn = new javax.swing.JTextField();
        paperIn = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        salesDistrictIn = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        phoneConIn = new javax.swing.JRadioButton();
        emailConIn = new javax.swing.JRadioButton();
        visitConIn = new javax.swing.JRadioButton();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        officeError = new javax.swing.JLabel();
        repIDError = new javax.swing.JLabel();
        firstNameErr = new javax.swing.JLabel();
        lastNameErr = new javax.swing.JLabel();
        contactError = new javax.swing.JLabel();
        bookError = new javax.swing.JLabel();
        paperError = new javax.swing.JLabel();
        validWrite = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sales Tracker");

        jLabel1.setText("Sales Rep ID:");

        jLabel2.setText("Sales Rep First Name");

        jLabel3.setText("Sales Rep Last Name");

        jLabel4.setText("Enter amount sold in each category");

        jLabel5.setText("Office Supplies");

        jLabel6.setText("Books");

        jLabel7.setText("Paper");

        jLabel8.setText("Select Sales District");

        salesDistrictIn.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "North", "South", "East", "West" }));

        jLabel9.setText("Perfered Contact Method");

        phoneConIn.setText("Phone");

        emailConIn.setText("E-Mail");

        visitConIn.setText("Visit");

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        officeError.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        officeError.setForeground(new java.awt.Color(255, 0, 0));
        officeError.setText("Error in this section");

        repIDError.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        repIDError.setForeground(new java.awt.Color(204, 0, 51));
        repIDError.setText("Rep ID Error");

        firstNameErr.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        firstNameErr.setForeground(new java.awt.Color(204, 0, 0));
        firstNameErr.setText("First Name Error");

        lastNameErr.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lastNameErr.setForeground(new java.awt.Color(204, 0, 0));
        lastNameErr.setText("Last Name Error");

        contactError.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        contactError.setForeground(new java.awt.Color(255, 0, 0));
        contactError.setText("Error in this section");

        bookError.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        bookError.setForeground(new java.awt.Color(255, 0, 0));
        bookError.setText("Error in this section");

        paperError.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        paperError.setForeground(new java.awt.Color(255, 0, 0));
        paperError.setText("Error in this section");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(repLNameIn))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(repFNameIn, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(repIDIn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(repIDError))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(salesDistrictIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(firstNameErr))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lastNameErr)))
                .addGap(130, 130, 130))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(offSupIn)
                                    .addComponent(bookIn)
                                    .addComponent(paperIn, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(officeError)
                                    .addComponent(bookError)
                                    .addComponent(paperError))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(phoneConIn)
                            .addComponent(emailConIn)
                            .addComponent(visitConIn)
                            .addComponent(contactError))
                        .addGap(61, 61, 61))))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(okButton)
                .addGap(34, 34, 34)
                .addComponent(validWrite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelButton)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(repIDIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(repIDError))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(repFNameIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameErr))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(repLNameIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameErr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(offSupIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(officeError))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(bookIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bookError))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(paperIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(paperError)))
                        .addGap(40, 40, 40)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(phoneConIn)
                        .addGap(18, 18, 18)
                        .addComponent(emailConIn)
                        .addGap(18, 18, 18)
                        .addComponent(visitConIn)
                        .addGap(18, 18, 18)
                        .addComponent(contactError)))
                .addGap(18, 18, 18)
                .addComponent(salesDistrictIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton)
                    .addComponent(validWrite))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    //Upon hitting the cancel button the application will terminate    
        System.exit(0);
    }//GEN-LAST:event_cancelButtonActionPerformed
//The following is the actions and validation that occurs when the OK button is pressed
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
//Set and define variables        
        SalesRep sr = new SalesRep();
        Helper h = new Helper();
        Path file = null;
        BufferedWriter bufferedWriter = null;
        boolean allDataValid = true;
        boolean validName = true;
        boolean validSale;
        String validFname = null;
        String validLname = null;
        double validOffSupp = 0;
        double validBook = 0;
        double validPaper = 0;
        
//Get text from the window and validate the reprsentative ID number        
        String repIDTest = repIDIn.getText();
        int validRepID = h.getValidID(repIDTest);
        if (validRepID == 000){
            allDataValid = false;
            repIDError.setText("Not a valid rep ID. Please re-enter");
            repIDError.setVisible(true);
            validWrite.setVisible(false);
        }else {
            repIDError.setVisible(false); 
        }
//Get the sales rep first name from window and validate that its a valid entry        
        validName = h.getValidName(repFNameIn.getText());
        if (validName){
            validFname = repFNameIn.getText();
            firstNameErr.setVisible(false);
        }else {
            allDataValid = false;
            firstNameErr.setText("Please re-enter a valid first name");
            firstNameErr.setVisible(true);
            validWrite.setVisible(false);
        }
//Get the sales rep last name from window and validate that its a valid entry            
        validName = h.getValidName(repLNameIn.getText());
        if (validName){
            validLname = repLNameIn.getText();
            lastNameErr.setVisible(false);
        }else {
            allDataValid = false;
            lastNameErr.setText("Please re-enter a valid last name");
            lastNameErr.setVisible(true);
            validWrite.setVisible(false);
        }
//Get the total from the window and make sure its a valid dollar amount -- Office Supply  
        validSale = h.getValidSale(offSupIn.getText());
        if (validSale == true){
            validOffSupp = Double.parseDouble(offSupIn.getText());
            officeError.setVisible(false);
        }else {
            allDataValid = false;
            officeError.setText("Please enter a valid office supply total");
            officeError.setVisible(true);
            validWrite.setVisible(false);
        }
//Get the total from the window and make sure its a valid dollar amount -- Books          
        validSale = h.getValidSale(bookIn.getText());
        if (validSale == true){
            validBook = Double.parseDouble(bookIn.getText());
            bookError.setVisible(false);
        }else {
            allDataValid = false;
            bookError.setText("Please enter a valid book total");
            bookError.setVisible(true);
            validWrite.setVisible(false);
        }
//Get the total from the window and make sure its a valid dollar amount -- Paper           
        validSale = h.getValidSale(paperIn.getText());
        if (validSale == true){
            validPaper = Double.parseDouble(paperIn.getText());
            paperError.setVisible(false);
        }else {
            allDataValid = false;
            paperError.setText("Please enter a valid paper total");
            paperError.setVisible(true);
            validWrite.setVisible(false);
        }
//Make sure that at least one of the contact methods is selected        
        if ((phoneConIn.isSelected()) || (emailConIn.isSelected()) || visitConIn.isSelected()){
            contactError.setVisible(false);
        }else{
            allDataValid = false;
            contactError.setText("A preferred contact method must be selected");
            contactError.setVisible(true);
            validWrite.setVisible(false);
        }
        
//Get the selected sales district and then cast it to a string in order to save the information
        Object saleDist = salesDistrictIn.getSelectedItem();
        String validSDist = (String) saleDist;
//Once all of the data has been validated and is valid then populate the Sales Rep class 
//and then call a helper component to print it to a file        
        if (allDataValid){
            //Build class instance with valid data
            sr.setSalesRepID(validRepID);
            sr.setFirstName(validFname);
            sr.setLastName(validLname);
            sr.setOffSupp(validOffSupp);
            sr.setBooks(validBook);
            sr.setPaper(validPaper);
            sr.setPhone(phoneConIn.isSelected());
            sr.setEmail(emailConIn.isSelected());
            sr.setVisit(visitConIn.isSelected());
            sr.setSalesDist(validSDist);
            JOptionPane.showMessageDialog(this, sr);
            //Call component to write the data to a file
            try{
                h.wtiteValidData2(sr);
                System.out.println("Valid write");
                //reset fields for next entry
                repIDIn.setText("");
                repFNameIn.setText("");
                repLNameIn.setText("");
                offSupIn.setText("");
                bookIn.setText("");
                paperIn.setText("");
                phoneConIn.setSelected(false);
                emailConIn.setSelected(false);
                visitConIn.setSelected(false);
                validWrite.setVisible(true);
                validWrite.setText("Data successfully written");
                validWrite.setForeground(Color.blue);
            }catch (IOException e){
                System.out.println("error writing to file");     
                validWrite.setVisible(true);
                validWrite.setText("Data not written to file");
                validWrite.setForeground(Color.red);
            }
        }//end if data valid
    //ok button action    
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesTracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesTracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesTracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesTracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesTracker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bookError;
    private javax.swing.JTextField bookIn;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel contactError;
    private javax.swing.JRadioButton emailConIn;
    private javax.swing.JLabel firstNameErr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lastNameErr;
    private javax.swing.JTextField offSupIn;
    private javax.swing.JLabel officeError;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel paperError;
    private javax.swing.JTextField paperIn;
    private javax.swing.JRadioButton phoneConIn;
    private javax.swing.JTextField repFNameIn;
    private javax.swing.JLabel repIDError;
    private javax.swing.JTextField repIDIn;
    private javax.swing.JTextField repLNameIn;
    private javax.swing.JComboBox salesDistrictIn;
    private javax.swing.JLabel validWrite;
    private javax.swing.JRadioButton visitConIn;
    // End of variables declaration//GEN-END:variables
}
